name: Michael Stiso
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc6621'
    - '#ff0000'
    - '#ffffff'
    - '#ffff00'
    - '#ffcccc'
  brandStrength: 0.09564942959696054
  lightness: 0.7752349162474275
  saturation: 0.9922280088067055
  rhythmicContrast: 0.7780885335523635
purpose: []
